apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: digibank
data:
  default.conf: |
    server {
        listen       80;
        server_name             _;
        root                    /usr/share/nginx/html;    
        underscores_in_headers on;
        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            add_header Access-Control-Allow-Origin "https://cdn.signalfx.com";
            proxy_pass_request_headers      on; 
            proxy_pass http://digital-bank-svc.digibank.svc.cluster.local:8080;  
            
            sub_filter      <head>
            {{ .Values.nginx.snippet }}
            sub_filter_once on;        

        }
    }