apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: digital-bank-mysql
  namespace: digibank
spec:
  containers:
  - image: mysql:8.0
    imagePullPolicy: Always
    name: mysql
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    ports:
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Demo123!"
    - name: MYSQL_USER
      value: "digitaluser"
    - name: MYSQL_PASSWORD
      value: "Demo123!"
    - name: MYSQL_DATABASE
      value: "digitalbank"
  restartPolicy: Always
