apiVersion: v1
kind: Service
metadata:
  name: digital-bank-backends-atm-svc
  namespace: digibank-backends
spec:
  selector:
    tier-name: backend-atm
  ports:
    - name: http-credit
      port: 8081  
      targetPort: atm-port
  type: LoadBalancer      