apiVersion: v1
data:
  SPRING_DATASOURCE_PLATFORM: {{ .Values.configMap.mysql.SPRING_DATASOURCE_PLATFORM }}
  SPRING_DATASOURCE_URL: {{ .Values.configMap.mysql.SPRING_DATASOURCE_URL }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: {{ .Values.configMap.mysql.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }}
kind: ConfigMap
metadata:
  name: cm-digibank-db
  namespace: digibank