apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: atm-nginx
  name: atm-nginx
  namespace: digibank-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: atm-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
