apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: digital-bank-mysql-svc
  namespace: digibank
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
