#FROM : https://github.com/signalfx/opentelemetry-demo/blob/main/splunk/otelcol-config.yml
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  http_forwarder:
    ingress:
      endpoint: 0.0.0.0:6060
    egress:
      # TODO: Ensure this is set properly
      endpoint: "https://api.${SPLUNK_REALM}.signalfx.com"
  zpages:
receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  sapm:
    endpoint: 0.0.0.0:7276
  signalfx:
    endpoint: 0.0.0.0:9943
  # This section is used to collect OpenTelemetry metrics
  # Even if just a SignalFx APM customer, these metrics are included
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
                # If you want to use the environment filter
                # In the SignalFx dashboard
                #labels:
              #environment: demo
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: '.*grpc_io.*'
              action: drop

processors:
  batch:
  # Optional: If you have a different environment tag name
  # If this option is enabled it must be added to the pipeline section below
  attributes/copyfromexistingkey:
    actions:
    - key: environment
      from_attribute: DEPLOYMENT_ENV
      action: upsert

  # Optional: If you want to add an environment tag
  # If this option is enabled it must be added to the pipeline section below
  attributes/newenvironment:
    actions:
    - key: environment
      value: "digibanknginx"
      action: insert
  resourcedetection:
    detectors:
      - env
      - system
    timeout: 10s
    override: true

exporters:

  debug:
    verbosity: detailed
  logging:
    verbosity: detailed

  # Traces
  sapm:
    # TODO: Ensure this is set properly
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    # TODO: Ensure this is set properly
    endpoint: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace"
  # Metrics
  signalfx:
    # TODO: Ensure this is set properly
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    # TODO: Ensure this is set properly
    realm: "${SPLUNK_REALM}"
    sync_host_metadata: true

service:
  extensions: [health_check, http_forwarder, zpages]
#  telemetry:
#    logs:
#      level: "debug"

  pipelines:
    traces:
      receivers: [otlp, sapm]
      processors: [attributes/newenvironment,attributes/copyfromexistingkey,batch, resourcedetection]
      exporters: [ debug,logging,sapm, signalfx ]
    metrics:
      receivers: [otlp, signalfx, prometheus]
      processors: [batch, resourcedetection]
      exporters: [signalfx]

